const API='/api/v1';let token=localStorage.getItem('mlai_token');
async function api(path,opts={}){opts.headers={...(opts.headers||{}),'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})};const r=await fetch(API+path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);return r.json()}
function login(){document.getElementById('app').innerHTML=`<div class="wrap"><div class="card" style="max-width:440px;margin:12vh auto"><h1>ML Affiliate AI</h1><p class="muted">Seu painel automático de afiliados.</p><label>E-mail</label><input id="email" class="input" type="email" autocomplete="username"><label>Senha</label><input id="password" class="input" type="password" autocomplete="current-password"><div id="err" class="error"></div><button class="btn" onclick="doLogin()">Entrar</button></div></div>`}
async function doLogin(){try{const d=await api('/auth/login',{method:'POST',body:JSON.stringify({email:email.value,password:password.value})});token=d.token;localStorage.setItem('mlai_token',token);dashboard()}catch(e){document.getElementById('err').textContent='E-mail ou senha inválidos.'}}
function productCard(p){return `<div class="card product"><div style="display:flex;gap:14px;align-items:center"><img src="${p.thumbnail||''}" style="width:72px;height:72px;object-fit:contain;border-radius:10px;background:#f5f5f5" onerror="this.style.display='none'"><div style="flex:1"><strong>${p.title||''}</strong><div class="muted">R$ ${Number(p.price||0).toFixed(2)} · ${p.discountPercent||0}% desconto · ⭐ ${p.rating??'—'} · ${p.reviewsCount||0} avaliações</div></div><div><strong>Score ${p.score}</strong></div></div><div style="margin-top:10px;font-size:12px" class="muted">Demanda: ${p.dataQuality?.demand} · Conversão: ${p.dataQuality?.conversion} · Comissão: ${p.dataQuality?.commission}</div><div style="margin-top:10px"><a class="btn alt" href="${p.permalink||'#'}" target="_blank" rel="noopener">Ver no Mercado Livre</a></div></div>`}
async function hunter(){document.getElementById('hunter').innerHTML=`<div class="card"><h2>Product Hunter</h2><p class="muted">Pesquise produtos reais do Mercado Livre Brasil e veja o score calculado com os dados disponíveis.</p><div style="display:flex;gap:8px"><input id="productQuery" class="input" placeholder="Ex.: cafeteira, celular, air fryer" style="flex:1"><button class="btn" onclick="searchProducts()">Pesquisar</button></div><div id="results" style="margin-top:14px"></div></div>`}
async function searchProducts(){const q=document.getElementById('productQuery').value.trim();if(!q)return;const box=document.getElementById('results');box.innerHTML='<p class="muted">Buscando...</p>';try{const d=await api('/products/search?q='+encodeURIComponent(q));box.innerHTML=(d.items||[]).map(productCard).join('')||'<p class="muted">Nenhum produto encontrado.</p>'}catch(e){box.innerHTML='<p class="error">Não foi possível buscar produtos agora.</p>'}}
async function dashboard(){try{const me=await api('/auth/me');const st=await api('/marketplace/mercadolivre/status');document.getElementById('app').innerHTML=`<div class="wrap"><div class="top"><div><h1>ML Affiliate AI</h1><div class="muted">Olá, ${me.name}</div></div><button class="btn alt" onclick="logout()">Sair</button></div><div class="grid"><div class="card"><div class="muted">Mercado Livre</div><h2>${st.connected?'Conectado':'Não conectado'}</h2><p>${st.configured?'Integração configurada':'Falta configurar as credenciais da aplicação'}</p>${st.connected?'':'<button class="btn" onclick="connectML()">Conectar Mercado Livre</button>'}</div><div class="card"><div class="muted">Product Hunter</div><h2>Operacional</h2><p>Busca real + persistência + score.</p><button class="btn" onclick="hunter()">Abrir Product Hunter</button></div><div class="card"><div class="muted">Regra financeira</div><h2>100% protegido</h2><p>Nenhum gasto sem sua aprovação.</p></div></div><div id="hunter" style="margin-top:16px"></div><div class="card" style="margin-top:16px"><h2>Estado do sistema</h2><p>✓ OAuth Mercado Livre conectado</p><p>✓ Product Hunter com dados reais</p><p>✓ Score calculado e histórico salvo</p><p>✓ Sem execução financeira automática</p><p class="muted">Conversão, comissão e tendência só serão usados quando uma API oficial fornecer esses dados. Nunca são inventados.</p></div></div>`}catch(e){token=null;localStorage.removeItem('mlai_token');login()}}
async function connectML(){try{const d=await api('/marketplace/mercadolivre/connect-url');window.location.href=d.url}catch(e){alert('Não foi possível iniciar a conexão com o Mercado Livre.')}}
async function logout(){try{await api('/auth/logout',{method:'POST'})}catch{}localStorage.removeItem('mlai_token');token=null;login()}
if(token)dashboard();else login();
