(() => {
  const API='/api/v1';
  const token=()=>localStorage.getItem('mlai_token')||'';
  const escValue=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const call=async(path,opts={})=>{opts.headers={...(opts.headers||{}),'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})};const r=await fetch(API+path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);return r.json()};
  function showAffiliate(productUrl){
    if(!productUrl)return;
    let modal=document.getElementById('affiliateLinkModal');
    if(!modal){
      modal=document.createElement('div');modal.id='affiliateLinkModal';modal.style='position:fixed;inset:0;background:rgba(0,0,0,.55);z-index:99999;display:flex;align-items:center;justify-content:center;padding:18px';
      modal.innerHTML='<div style="background:#fff;border-radius:16px;max-width:520px;width:100%;padding:20px;box-shadow:0 12px 40px rgba(0,0,0,.25)"><h2 style="margin-top:0">🔗 Gerar link de afiliado</h2><p>1. Copie o link abaixo.</p><input id="affiliateProductUrl" class="input" style="width:100%;box-sizing:border-box" readonly><p>2. Abra o Portal de Afiliados do Mercado Livre e use o <b>Gerador de Links</b>.</p><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:14px"><button id="copyAffiliateProduct" class="btn">📋 Copiar link</button><a id="openAffiliatePortal" class="btn alt" href="https://www.mercadolivre.com.br/afiliados" target="_blank" rel="noopener">Abrir Portal de Afiliados</a><button id="closeAffiliateModal" class="btn alt">Fechar</button></div><p class="muted small" style="margin-bottom:0">Depois de gerar o link oficial <b>meli.la</b>, volte ao produto e use “Vincular link”.</p></div>';
      document.body.appendChild(modal);
      document.getElementById('closeAffiliateModal').onclick=()=>modal.remove();
      document.getElementById('copyAffiliateProduct').onclick=async()=>{const v=document.getElementById('affiliateProductUrl').value;try{await navigator.clipboard.writeText(v);document.getElementById('copyAffiliateProduct').textContent='✓ Copiado';}catch{document.getElementById('affiliateProductUrl').select();document.execCommand('copy');document.getElementById('copyAffiliateProduct').textContent='✓ Copiado';}};
    }
    document.getElementById('affiliateProductUrl').value=productUrl;
    modal.style.display='flex';
  }
  async function load(){
    const box=document.getElementById('hunterAutoResults');if(!box)return;
    box.innerHTML='<p class="muted">Carregando produtos encontrados pelo Hunter...</p>';
    try{
      const products=await call('/products/top');
      box.innerHTML=`<div class="section-title" style="margin-top:18px"><h2>Produtos encontrados</h2><span class="muted">Atualizado automaticamente</span></div>`+
      ((products||[]).length?products.map(p=>{const active=!!p.affiliateUrl;const hasPrice=Number(p.price)>0;const productUrl=p.productUrl||'';const image=p.imageUrl||'';return `<div class="card product" style="margin-top:10px;cursor:pointer" data-product-card="${escValue(p.id)}"><div class="product-row">${image&&productUrl?`<a href="${escValue(productUrl)}" target="_blank" rel="noopener" onclick="event.stopPropagation()"><img src="${escValue(image)}" class="product-img" alt="${escValue(p.title||'Produto')}" onerror="this.style.display='none'"></a>`:image?`<img src="${escValue(image)}" class="product-img" alt="${escValue(p.title||'Produto')}" onerror="this.style.display='none'">`:''}<div class="product-main" style="min-width:0">${productUrl?`<a href="${escValue(productUrl)}" target="_blank" rel="noopener" style="text-decoration:none;color:inherit" onclick="event.stopPropagation()"><strong>${escValue(p.title||'Produto')}</strong></a>`:`<strong>${escValue(p.title||'Produto')}</strong>`}<div class="muted">${hasPrice?'R$ '+Number(p.price).toFixed(2):'Preço não informado'} · ${p.discountPercent?Number(p.discountPercent).toFixed(0)+'% desconto · ':''}${p.categoryName?escValue(p.categoryName)+' · ':''}Score ${p.latestScore??'—'}</div><div class="muted small">Produto encontrado pelo Hunter. O link de afiliado só será liberado depois da geração oficial no Mercado Livre.</div></div><div class="score-pill">${active?'🟢 AFILIADO ATIVO':'🟡 AGUARDANDO LINK'}</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px">${productUrl&&!active?`<button class="btn alt" data-generate-link="${escValue(p.id)}">🔗 Gerar link de afiliado</button>`:''}${productUrl?`<a class="btn alt" href="${escValue(productUrl)}" target="_blank" rel="noopener">Abrir produto</a>`:''}${active?`<a class="btn" href="${escValue(p.affiliateUrl)}" target="_blank" rel="noopener">Abrir link afiliado</a>`:`<input class="input" style="min-width:260px;flex:1" data-affiliate-input="${escValue(p.id)}" placeholder="Cole o link oficial meli.la"><button class="btn" data-affiliate-save="${escValue(p.id)}">Vincular link</button>`}</div></div>`}).join(''):'<div class="card"><p class="muted">Nenhum produto pesquisado ainda. Se o sistema estiver ligado, o Hunter preencherá esta área automaticamente.</p></div>');
      box.querySelectorAll('[data-product-card]').forEach(card=>card.onclick=e=>{if(e.target.closest('a,button,input'))return;const p=(products||[]).find(x=>String(x.id)===String(card.dataset.productCard));if(p?.productUrl)window.open(p.productUrl,'_blank','noopener');});
      box.querySelectorAll('[data-generate-link]').forEach(btn=>btn.onclick=()=>{const p=(products||[]).find(x=>String(x.id)===String(btn.dataset.generateLink));showAffiliate(p?.productUrl)});
      box.querySelectorAll('[data-affiliate-save]').forEach(btn=>btn.onclick=async()=>{try{const id=btn.dataset.affiliateSave;const input=box.querySelector(`[data-affiliate-input="${id}"]`);await call('/products/'+encodeURIComponent(id)+'/affiliate-link',{method:'POST',body:JSON.stringify({affiliateUrl:input.value.trim()})});btn.textContent='✓ Vinculado';await load()}catch(e){alert('Use somente o link oficial de afiliado meli.la gerado pelo Mercado Livre.')}});
    }catch(e){box.innerHTML='<div class="card"><p class="error">Não foi possível carregar os produtos do Hunter agora.</p><button class="btn alt" onclick="window.__hunterLoad&&window.__hunterLoad()">Tentar novamente</button></div>'}
  }
  function mount(){const hunter=document.getElementById('hunter');if(!hunter||document.getElementById('hunterAutoResults'))return;const box=document.createElement('div');box.id='hunterAutoResults';hunter.appendChild(box);window.__hunterLoad=load;load()}
  new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});setTimeout(mount,500);
})();