(() => {
const API='/api/v1';
const token=()=>localStorage.getItem('mlai_token')||'';
const call=async(path,opts={})=>{opts.headers={...(opts.headers||{}),'Content-Type':'application/json',...(token()?{Authorization:'Bearer '+token()}:{})};const r=await fetch(API+path,opts);if(!r.ok)throw new Error((await r.text())||r.statusText);return r.json()};
const badge=(ok,label)=>`<span class="status ${ok?'ok-bg':'warn'}">${ok?'●':'○'} ${label}</span>`;
async function queue(box){const pending=await call('/products/affiliate-pending');const area=box.querySelector('[data-pending]');box.querySelector('[data-pending-title]').textContent=`Pendências de link (${pending.length})`;area.innerHTML=pending.length?pending.map(p=>`<div style="padding:10px 0;border-top:1px solid rgba(127,127,127,.15)"><b>${String(p.title||'').slice(0,80)}</b><div class="muted small">${p.externalProductId||p.id} · ${p.price?'R$ '+Number(p.price).toFixed(2):'Preço não informado'}</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-top:6px"><a class="btn alt" target="_blank" rel="noopener" href="${p.productUrl}">Abrir produto no Mercado Livre</a><button class="btn alt" data-copy="${p.id}">Copiar página</button><input class="input" style="min-width:260px" data-aff="${p.id}" placeholder="Link oficial meli.la"><button class="btn" data-save="${p.id}">Vincular</button></div></div>`).join(''):'<p class="muted">✓ Nenhuma pendência.</p>';
area.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const p=pending.find(x=>x.id===b.dataset.copy);await navigator.clipboard?.writeText(p?.productUrl||'');b.textContent='✓ Copiado'});
area.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{try{const input=area.querySelector(`[data-aff="${b.dataset.save}"]`);await call('/products/'+b.dataset.save+'/affiliate-link',{method:'POST',body:JSON.stringify({affiliateUrl:input.value.trim()})});b.textContent='✓ Vinculado';await refresh()}catch(_){alert('Use o link oficial de afiliado gerado pelo Mercado Livre.')}});
box.querySelector('[data-copy-all]').onclick=async()=>{await navigator.clipboard?.writeText(pending.map(p=>`${p.externalProductId||p.id}\t${p.title}\t${p.productUrl}`).join('\n'));box.querySelector('[data-copy-all]').textContent='✓ Lista copiada'};
}
async function refresh(){const box=document.getElementById('opsCenter');if(!box)return;try{const[ml,tt,ig,pin,a]=await Promise.all([call('/marketplace/mercadolivre/status'),call('/marketplace/tiktok/status'),call('/marketplace/instagram/status'),call('/marketplace/pinterest/status'),call('/automation/status')]);box.querySelector('[data-status]').innerHTML=[badge(ml.connected,'Mercado Livre'),badge(tt.connected,'TikTok'),badge(ig.connected,'Instagram'),badge(pin.connected,'Pinterest'),badge(a.enabled,'AUTOMAÇÃO '+(a.enabled?'LIGADA':'DESLIGADA'))].join(' ');box.querySelector('[data-detail]').textContent=a.enabled?(a.running?'🟠 Hunter trabalhando agora':'🟢 Automação ligada — próxima busca em até '+a.intervalHours+'h'):'🔴 Automação desligada — nada será pesquisado automaticamente.';box.querySelector('[data-start]').disabled=!!a.enabled;box.querySelector('[data-stop]').disabled=!a.enabled;box.querySelector('[data-run]').disabled=!a.enabled;const top=await call('/products/top');box.querySelector('[data-products]').innerHTML=(top||[]).slice(0,5).map(p=>`<div style="padding:8px 0;border-top:1px solid rgba(127,127,127,.15)"><b>${String(p.title||'').slice(0,70)}</b><div class="muted small">Score ${p.latestScore??'-'} · ${p.affiliateUrl?'🟢 AFILIADO ATIVO':'🟡 AGUARDANDO LINK'}</div></div>`).join('')||'<p class="muted">Nenhum produto pesquisado.</p>';await queue(box)}catch(e){box.querySelector('[data-detail]').textContent='Não foi possível atualizar o diagnóstico.'}}
function mount(){if(document.getElementById('opsCenter'))return;const home=document.getElementById('home');if(!home)return;const el=document.createElement('div');el.id='opsCenter';el.className='card safety';el.innerHTML=`<div style="width:100%"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap"><div><strong>⚙ Centro operacional</strong><p class="muted">Controle central do ML Affiliate AI.</p></div><div data-status class="status-list"></div></div><div data-detail class="muted small" style="margin:10px 0">Verificando...</div><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn" data-start>▶ LIGAR SISTEMA</button><button class="btn" data-stop style="background:#b42318">■ DESLIGAR / EMERGÊNCIA</button><button class="btn alt" data-run>Executar Hunter agora</button><button class="btn alt" data-copy-all>Copiar pendências</button><button class="btn alt" data-refresh>Atualizar</button><button class="btn alt" data-open-ml>Portal de Afiliados</button></div><h3 style="margin-top:18px">Fila diária — links de afiliado</h3><p class="muted small">O Hunter pesquisa produtos sozinho quando ligado. O Mercado Livre atualmente orienta a geração dos links pelo Gerador de Links/Barra de Afiliados; por isso, quando não houver método oficial disponível para geração automática, o produto fica nesta fila até você vincular o link oficial.</p><h4 data-pending-title>Carregando...</h4><div data-pending><p class="muted">Carregando...</p></div><h3 style="margin-top:18px">Produtos encontrados</h3><div data-products><p class="muted">Carregando...</p></div><p class="muted small">🔒 Segurança: produto sem link oficial confirmado não entra na loja, não gera conteúdo e não é publicado. O botão de emergência impede novas execuções automáticas.</p></div>`;
home.appendChild(el);
el.querySelector('[data-start]').onclick=async()=>{await call('/automation/start',{method:'POST'});await refresh()};
el.querySelector('[data-stop]').onclick=async()=>{if(!confirm('Desligar toda a automação agora?'))return;await call('/automation/stop',{method:'POST'});await refresh()};
el.querySelector('[data-run]').onclick=async()=>{try{await call('/automation/run',{method:'POST'});await refresh()}catch(_){alert('Ligue o sistema primeiro.')}};
el.querySelector('[data-refresh]').onclick=refresh;
el.querySelector('[data-open-ml]').onclick=()=>window.open('https://www.mercadolivre.com.br/l/afiliados-home','_blank');
refresh()}
new MutationObserver(mount).observe(document.documentElement,{childList:true,subtree:true});setTimeout(mount,700);
})();
